# permissions for end users to view managedschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managedscheduler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hydra-operator
    app.kubernetes.io/part-of: hydra-operator
    app.kubernetes.io/managed-by: kustomize
  name: managedscheduler-viewer-role
rules:
- apiGroups:
  - iaas.homelabs.io
  resources:
  - managedschedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iaas.homelabs.io
  resources:
  - managedschedulers/status
  verbs:
  - get
