apiVersion: iaas.homelabs.io/v1alpha1
kind: ManagedCloudControllerManager
metadata:
  labels:
    app.kubernetes.io/name: managedcloudcontrollermanager
    app.kubernetes.io/instance: managedcloudcontrollermanager-sample
    app.kubernetes.io/part-of: hydra-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hydra-operator
  name: managedcloudcontrollermanager-sample
spec:
  # TODO(user): Add fields here
