apiVersion: iaas.homelabs.io/v1alpha1
kind: ManagedApiServer
metadata:
  labels:
    app.kubernetes.io/name: managedapiserver
    app.kubernetes.io/instance: managedapiserver-sample
    app.kubernetes.io/part-of: hydra-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hydra-operator
  name: managedapiserver-sample
spec:
  # TODO(user): Add fields here
