apiVersion: iaas.homelabs.io/v1alpha1
kind: ManagedEtcd
metadata:
  labels:
    app.kubernetes.io/name: managedetcd
    app.kubernetes.io/instance: managedetcd-sample
    app.kubernetes.io/part-of: hydra-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hydra-operator
  name: managedetcd-sample
spec:
  # TODO(user): Add fields here
